import Head from "next/head";

import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>Linode hackathon boilerplate</h3>

        {session ? (
          <>
            <p>
              Signed in as {session.user.email} <br />
            </p>
            <img
              width="50px"
              height="50px"
              src={session.user.image}
              alt="profile pic"
            />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        ) : (
          <>
            Not signed in <br />
            <button onClick={() => signIn()}>Sign in</button>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/biomathcode/boilerplate"
          target="_blank"
          rel="noopener noreferrer"
        >
          Git clone me{" "}
        </a>
      </footer>
    </div>
  );
}
